"""initial_schema"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3f8d4073d87a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_insights",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_insights", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_insights_created_at"), ["created_at"], unique=False)

    op.create_table(
        "provider_metrics",
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    with op.batch_alter_table("provider_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_metrics_created_at"), ["created_at"], unique=False)

    op.create_table(
        "social_accounts",
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("credential_ref", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("daily_limit", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_social_accounts_created_at"), ["created_at"], unique=False)

    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("authorization_type", sa.String(length=32), nullable=False),
        sa.Column("authorization_note", sa.Text(), nullable=False),
        sa.Column("authorized_platforms", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("routing", sa.String(length=20), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_created_at"), ["created_at"], unique=False)

    op.create_table(
        "strategy_metrics",
        sa.Column("dimension", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.Column("median_views", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dimension", "label"),
    )
    with op.batch_alter_table("strategy_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_strategy_metrics_created_at"), ["created_at"], unique=False)

    op.create_table(
        "system_jobs",
        sa.Column("idempotency_key", sa.String(length=250), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("system_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_jobs_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_jobs_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_jobs_status"), ["status"], unique=False)

    op.create_table(
        "system_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("autopilot", sa.Boolean(), nullable=False),
        sa.Column("stop_all_posting", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("posting_times", sa.JSON(), nullable=False),
        sa.Column("daily_limit", sa.Integer(), nullable=False),
        sa.Column("min_interval", sa.Integer(), nullable=False),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("policy_filters", sa.JSON(), nullable=False),
        sa.Column("learning_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_videos",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    with op.batch_alter_table("source_videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_videos_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_videos_source_id"), ["source_id"], unique=False)

    op.create_table(
        "api_usage",
        sa.Column("idempotency_key", sa.String(length=250), nullable=False),
        sa.Column("source_video_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("units", sa.Float(), nullable=False),
        sa.Column("unit_type", sa.String(length=30), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("actual_tokens", sa.Integer(), nullable=True),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("api_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_usage_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_usage_provider"), ["provider"], unique=False)

    op.create_table(
        "provider_projects",
        sa.Column("source_video_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_video_id", "provider"),
    )
    with op.batch_alter_table("provider_projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_projects_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_provider_projects_source_video_id"), ["source_video_id"], unique=False
        )

    op.create_table(
        "clips",
        sa.Column("source_video_id", sa.String(length=36), nullable=False),
        sa.Column("provider_project_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("ranges", sa.JSON(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.String(length=250), nullable=True),
        sa.Column("provider_score", sa.Float(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("topic", sa.String(length=150), nullable=False),
        sa.Column("hook_style", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=True),
        sa.Column("duplicate_of", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("policy_flags", sa.JSON(), nullable=False),
        sa.Column("manually_approved", sa.Boolean(), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["clips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_project_id"],
            ["provider_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_project_id", "external_id"),
    )
    with op.batch_alter_table("clips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clips_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_clips_overall_score"), ["overall_score"], unique=False)
        batch_op.create_index(batch_op.f("ix_clips_source_video_id"), ["source_video_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_clips_status"), ["status"], unique=False)

    op.create_table(
        "clip_embeddings",
        sa.Column("clip_id", sa.String(length=36), nullable=False),
        sa.Column("vector", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clip_id"),
    )
    with op.batch_alter_table("clip_embeddings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clip_embeddings_created_at"), ["created_at"], unique=False)

    op.create_table(
        "clip_scores",
        sa.Column("clip_id", sa.String(length=36), nullable=False),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("rubric_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clip_id"),
    )
    with op.batch_alter_table("clip_scores", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clip_scores_created_at"), ["created_at"], unique=False)

    op.create_table(
        "scheduled_posts",
        sa.Column("clip_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("remote_state", sa.JSON(), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["social_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "scheduled_at"),
        sa.UniqueConstraint("clip_id", "account_id"),
    )
    with op.batch_alter_table("scheduled_posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scheduled_posts_clip_id"), ["clip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scheduled_posts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_scheduled_posts_scheduled_at"), ["scheduled_at"], unique=False)

    op.create_table(
        "published_posts",
        sa.Column("scheduled_post_id", sa.String(length=36), nullable=False),
        sa.Column("clip_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_post_id"],
            ["scheduled_posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scheduled_post_id"),
    )
    with op.batch_alter_table("published_posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_published_posts_clip_id"), ["clip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_published_posts_created_at"), ["created_at"], unique=False)

    op.create_table(
        "analytics_snapshots",
        sa.Column("published_post_id", sa.String(length=36), nullable=False),
        sa.Column("checkpoint_hours", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("normalized", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["published_post_id"],
            ["published_posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("published_post_id", "checkpoint_hours"),
    )
    with op.batch_alter_table("analytics_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analytics_snapshots_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analytics_snapshots_published_post_id"), ["published_post_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analytics_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analytics_snapshots_published_post_id"))
        batch_op.drop_index(batch_op.f("ix_analytics_snapshots_created_at"))

    op.drop_table("analytics_snapshots")
    with op.batch_alter_table("published_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_published_posts_created_at"))
        batch_op.drop_index(batch_op.f("ix_published_posts_clip_id"))

    op.drop_table("published_posts")
    with op.batch_alter_table("scheduled_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_posts_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_scheduled_posts_created_at"))
        batch_op.drop_index(batch_op.f("ix_scheduled_posts_clip_id"))

    op.drop_table("scheduled_posts")
    with op.batch_alter_table("clip_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clip_scores_created_at"))

    op.drop_table("clip_scores")
    with op.batch_alter_table("clip_embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clip_embeddings_created_at"))

    op.drop_table("clip_embeddings")
    with op.batch_alter_table("clips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clips_status"))
        batch_op.drop_index(batch_op.f("ix_clips_source_video_id"))
        batch_op.drop_index(batch_op.f("ix_clips_overall_score"))
        batch_op.drop_index(batch_op.f("ix_clips_created_at"))

    op.drop_table("clips")
    with op.batch_alter_table("provider_projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_projects_source_video_id"))
        batch_op.drop_index(batch_op.f("ix_provider_projects_created_at"))

    op.drop_table("provider_projects")
    with op.batch_alter_table("api_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_usage_provider"))
        batch_op.drop_index(batch_op.f("ix_api_usage_created_at"))

    op.drop_table("api_usage")
    with op.batch_alter_table("source_videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_videos_source_id"))
        batch_op.drop_index(batch_op.f("ix_source_videos_created_at"))

    op.drop_table("source_videos")
    op.drop_table("users")
    op.drop_table("system_state")
    with op.batch_alter_table("system_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_system_jobs_kind"))
        batch_op.drop_index(batch_op.f("ix_system_jobs_due_at"))
        batch_op.drop_index(batch_op.f("ix_system_jobs_created_at"))

    op.drop_table("system_jobs")
    with op.batch_alter_table("strategy_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_metrics_created_at"))

    op.drop_table("strategy_metrics")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_created_at"))

    op.drop_table("sources")
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_social_accounts_created_at"))

    op.drop_table("social_accounts")
    with op.batch_alter_table("provider_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_metrics_created_at"))

    op.drop_table("provider_metrics")
    with op.batch_alter_table("ai_insights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_insights_created_at"))

    op.drop_table("ai_insights")
    # ### end Alembic commands ###
