const { chromium } = require(process.argv[2] || 'playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const output = path.resolve('artifacts');
  await fs.mkdir(output,{recursive:true});
  await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
  await page.getByLabel('Studio password').fill(process.env.CLIPBOT_TEST_PASSWORD || 'clipbot-local');
  await page.getByRole('button',{name:'Open studio'}).click();
  await page.getByRole('heading',{name:'Your studio, at a glance.'}).waitFor();
  const seed = page.getByRole('button',{name:'Load sample workflow'});
  if(await seed.count()) await seed.click();
  await page.getByText("The Builder's Journal",{exact:false}).first().waitFor({timeout:20000}).catch(()=>{});
  await page.locator('.recharts-area').first().waitFor();
  await page.screenshot({path:path.join(output,'overview-desktop.png'),fullPage:true,animations:'disabled'});
  for(const view of ['sources','clips','queue','analytics','insights','connections','settings']) {
    await page.goto('http://localhost:3000/'+view,{waitUntil:'networkidle'});
    await page.locator('main h1').waitFor();
    if(await page.getByText('backend is unavailable',{exact:false}).count()) throw Error('Backend unavailable on '+view);
  }
  await page.goto('http://localhost:3000/clips',{waitUntil:'networkidle'});
  await page.locator('.clip-card').first().click();
  await page.getByRole('dialog',{name:'A closer look'}).waitFor();
  await page.getByText('Platform copy & hooks',{exact:true}).click();
  await page.getByRole('button',{name:'Instagram',exact:true}).click();
  await page.getByRole('button',{name:'Copy for instagram'}).waitFor();
  await page.screenshot({path:path.join(output,'clip-review.png'),fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('textbox',{name:'Search clips'}).fill('zzzz-no-match');
  await page.getByRole('heading',{name:'No clips in this view'}).waitFor();
  await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'Your studio, at a glance.'}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=1);
  await page.screenshot({path:path.join(output,'overview-mobile.png'),fullPage:true,animations:'disabled'});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  if(overflow) throw Error('Mobile page has horizontal overflow');
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.getByRole('link',{name:'Sources',exact:true}).click();
  await page.getByRole('heading',{name:'Good content starts here.'}).waitFor();
  await browser.close();
  if(errors.length) throw Error(errors.join('\n'));
  console.log('Browser checks passed: sign in, demo import, all eight views, clip inspection, search and mobile navigation.');
  console.log('Screenshots: '+output);
})().catch(error=>{console.error(error);process.exit(1);});
